version: '3.9'

networks:
  app-network:
    driver: bridge

volumes:
  data:

services:
  redis:
    image: redis:latest
    container_name: redis-service
    ports:
      - '6379:6379'
    volumes:
      - data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-network

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "8001:8001"
    environment:
      - REDIS_URI=redis://redis:6379
    depends_on:
      - redis
    networks:
      - app-network